# .ci/bash.yml
version: v2.0
on:
  push: [ "*" ]
  mr: [ "*" ]
  tag: [ "*" ]

stages:
- name : "stage1: run"
  jobs:
    job1:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 0:60 gem5_input_part1 1 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320


    job2:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 60:120 gem5_input_part1 2 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job3:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 120:180 gem5_input_part2 3 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320


    job4:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 180:240 gem5_input_part2 4 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job5:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 240:300 gem5_input_part3 5 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job6:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 300:360 gem5_input_part3 6 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job7:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 360:420 gem5_input_part4 7 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320


    job8:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 420:480 gem5_input_part4 8 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job9:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 480:540 gem5_input_part5 9 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job10:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 540:600 gem5_input_part5 10 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job11:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 600:660 gem5_input_part6 11 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job12:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 660:720 gem5_input_part6 12 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job13:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 720:780 gem5_input_part7 13 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job14:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 780:840 gem5_input_part7 14 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job15:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 840:900 gem5_input_part8 15 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job16:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 900:960 gem5_input_part8 16 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job17:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 960:1020 gem5_input_part9 17 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320

    job18:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            bash ./scripts/build.sh
          name: "Building"

        - run: |
            bash ./scripts/test_all.sh 1020:1062 gem5_input_part9 18 /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ normal
          name: "test"
          timeout-minutes: 4320


- name : "stage2: report"
  jobs:
    job1:
      runs-on:
        pool-name: docker
        container:
          image: mirrors.tencent.com/gem5/gem5:v0.9.4
      timeout-minutes:
        4320
      steps:
        - checkout: self
          with:
            enableVirtualMergeBranch: false

        - run: |
            rm -rf /gem5_common_trace/env-scripts; cd /gem5_common_trace; git clone -b zql https://git.woa.com/qianlnzhang/env-scripts.git; 
          name: "git checkout env-scripts"
        - run: |
            python3 ./scripts/test_sc2006_simpoint_report.py --jobs_num 18 --repo_dir /$BK_CI_GIT_REPO_NAME/$BK_CI_GIT_REPO_BRANCH/$BK_CI_GIT_REPO_HEAD_COMMIT_ID/ --action normal
          name: "report"
        - run: |
            echo "::set-output name=coverage_report,type=report,label=测试报告,path=./::test.html"
          name: "Upload Test Report"

notices:
  # After the execution is finished, send Wechat notification.
  - type: wework-message
